### ISSUE TITLE
Supports dotnet watch inside container?

### ISSUE THREAD

**Issue by johnknoop** [nickvdyck/docker-watch#1]
I've noticed that when your dockerfile mounts the source as a volume into the container and runs `dotnet watch`, it doesn't detect changes in the source code. Do you know if this tool will help solve that?

**Comment by vandycknick** [comment]
Yes this tool is made specifically to fix the issue you just described. I tried to explain the reason for this  in my README (it's a bit tough to explain so sr if it didn't make much sense, I'll see if I can revise that).

Most tools work around the issue by falling back to polling for file changes which is also what the `dotnet watch` command will do when you set the following environment variable `DOTNET_USE_POLLING_FILE_WATCHER` : https://github.com/aspnet/AspNetCore/tree/master/src/Tools/dotnet-watch#environment-variables . When you use one of the official microsoft aspnet images this will automatically be set for you: https://github.com/dotnet/dotnet-docker/blob/041ee92829af883ff14377c95d4b6773ff483220/2.1/sdk/alpine3.7/amd64/Dockerfile#L26  and thus you will never notice that `dotnet watch` is falling back to polling.

So you actually have a few options here:
1. Set the `DOTNET_USE_POLLING_FILE_WATCHER` to true and fall back to polling
2. Use on of the official microsoft aspnet core docker images and not worry about how changes are detected.
3. Use this tool (`docker-watch`) and it will fix this issue for every mounted volume without changing your docker images. 😄 

Hope this helps 👍
